[build]
  publish = "dist/hoplaFly"
  command = "pnpm run build"
  functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "ng serve"
  port = 8888
  functions = "netlify/functions"
  publish = "dist/hoplaFly"
