[build]
  publish = "dist/hoplaFly"
  command = "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install && pnpm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/hoplaFly"
