[build]
  publish = "dist/hoplaFly"
  command = "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install && pnpm run build"
  functions = "netlify/functions"

[functions]
external_node_modules = [
  "mongodb",
  "bson",
  "@mongodb-js/saslprep",
  "mongodb-connection-string-url",
  "sparse-bitfield",
  "memory-pager"
]

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "ng serve"
  port = 8888
  functions = "netlify/functions"
  publish = "dist/hoplaFly"
